cuda: 2
data:
      path: './dataset'
      name: 'AmazonBook'
      LLM_info : 'LLM'
wandb : True
wandb_name : AB_experts_8_emb_512

### Training Ablation
Train : True
LoadPretrain : 0
KGPretrain : 0
debug : 0
isContrastive : 1 ## whether use contrastive learning
isApplyLLMinfo : 1
isConfiFilter : 1
ContrastiveSeperate: 0
ContrastiveFused : 1
train_kge : True
### Training Configuations
epoch : 1000
start_epoch : 0
seed : 2024
learning_rate : 0.0001
dataloader_n_workers : 8
embedding_dim : 512
num_experts : 8
loss_reg_weight : 0.0001
### Model Setting(Subgraph Extraction)
extract_batch_size : 32
max_sample_neighbors : 3
### LLM Load Information
delete_ratio : 0.08
add_ratio : 0.68
### Model Setting(KG Training)
kge_batch_size : 1024
kg_neg_size : 100
train_interval_kge : 1
entity_num_per_item : 8
item_num_per_entity : 8
kgcn : 'RGAT'
kg_p_drop : 0.2
### Model Setting(BPR Training)
bpr_batch_size : 2048
lightGCN_n_layers : 2
dropout : True
keep_prob : 0.8
A_split : False
ui_p_drop : 0.001
#### Constrastive Learning
nce_temperatue : 0.2
mix_ratio : 0.5
loss_con_weight : 0.1
gumbel_tau : 0.1
confidence_temperature : 10
### Evaluation
eval_interval : 1
topks : [10]
test_u_batch_size : 128
early_stop_epoch : 100
metrics : ['precision', 'recall', 'ndcg']
metric_decimal_place : 6
### Saving
load_path : ''
save_path : '/data/cairui/KG-LLM-REC/checkpoint/Model/'
save_interval : 1
