cuda: 5
data:
      name: 'AmazonBook'
### Training
seed: 2024
learning_rate : 0.001
epoch : 100
start_epoch : 0
batch_size : 16

### Model Setting
kg_neg_size : 100
max_sample_neighbors : 4
dataloader_n_workers : 4
embedding_dim : 200
hidden_embedding_dim : 400
isPretrain : 0
n_layers_lightgcn : 3
loss_kge_weight : 0.5
loss_reg_weight : 0.001

### Evaluation
save_path : '/data/cairui/KG-LLM-REC/'
eval_interval : 5
topks : [10, 20, 50]
test_u_batch_size : 128 