cuda: 7
data:
      path: './dataset'
      name: 'AmazonBook'
### Training
Train: False
seed: 514
learning_rate : 0.0001
epoch : 1000
start_epoch : 200
batch_size : 1024
### Model Setting
isPretrain : 0
kg_neg_size : 100
max_sample_neighbors : 3
dataloader_n_workers : 8
embedding_dim : 64
ent_embedding_dim : 64
rel_embedding_dim : 64
hidden_embedding_dim : 256
n_layers_lightgcn : 2
loss_kge_weight : 0.5
loss_reg_weight : 0.0001
#### Aggregator
mess_dropout : [0.1, 0.1, 0.1]
conv_dim_list : [64, 32, 16]
aggregation_type : 'bi-interaction'
#### Constrastive Learning
start_step : 0
end_step : 0
con_temperature : 0.2
loss_con_weight : 0.01
### Evaluation
load_path : 'epoch_1000_LightGCN_AB-layer2.ckpt'
special_save_hyper : 'AB-layer2'
save_path : '/data/cairui/KG-LLM-REC/'
eval_interval : 1
save_interval : 50
topks : [10, 50, 100]
test_u_batch_size : 1024
metrics : ['precision', 'recall', 'ndcg']
metric_decimal_place : 6
